services:
  drive-service:
    build:
      context: ./driveService
    container_name: driveService
    ports:
      - "9582:9582"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    networks:
      - app-network

  student-service:
    build:
      context: ./StudentService
    container_name: studentService
    ports:
      - "4001:4001"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    networks:
      - app-network

  auth-service:
    build:
      context: ./auth-service
    container_name: authService
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    networks:
      - app-network

  dashboard-service:
    build:
      context: ./dashboardService
    container_name: dashboardService
    ports:
      - "4003:4003"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/
    networks:
      - app-network

  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
