apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: bits-scalable-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: k8s-auth-service
        imagePullPolicy: Never
        ports:
        - containerPort: 4000