apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: bits-scalable-services
spec:
  type: NodePort
  selector:
    app: auth-service
  ports:
    - port: 4000
      targetPort: 4000
