apiVersion: v1
kind: Service
metadata:
  name: drive-service
  namespace: bits-scalable-services
spec:
  type: NodePort
  selector:
    app: drive-service
  ports:
    - port: 4002
      targetPort: 4002
